### ISSUE TITLE
 GPU Configuration for Training?

### ISSUE THREAD

**Issue by narsisn** [zbwxp/SegVit#11]
Thank you so much for your great work. 
Could you please provide information about the number and type of GPUs you used for training the models?

**Comment by AkideLiu** [comment]
I believe it refers to a different dataset. In the original answer, we utilized a node with 4 A100 GPUs, with each GPU processing 4 samples in parallel on Pascal dataset due to a smaller crop size. However, if you are training a larger ViT model with a crop size of 640×640, you might require 8 A100 GPUs with 80GB memory, with each GPU handling 2 samples (as done in the current version of SegViT). For the upcoming version, SegViT v2, we will release the code that enables the use of a ViT base model, which will help reduce the cost of reproduction. This release will be available soon.
